//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riêng tư.
        /// </summary>
        public static string _private {
            get {
                return ResourceManager.GetString("private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công khai.
        /// </summary>
        public static string _public {
            get {
                return ResourceManager.GetString("public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấp thuận.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã tồn tại.
        /// </summary>
        public static string accountExist {
            get {
                return ResourceManager.GetString("accountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm công việc mới.
        /// </summary>
        public static string addTask {
            get {
                return ResourceManager.GetString("addTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm người dùng.
        /// </summary>
        public static string addUser {
            get {
                return ResourceManager.GetString("addUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu trả lời.
        /// </summary>
        public static string ans {
            get {
                return ResourceManager.GetString("ans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu trả lời.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở về.
        /// </summary>
        public static string backToList {
            get {
                return ResourceManager.GetString("backToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung hoá đơn.
        /// </summary>
        public static string billContent {
            get {
                return ResourceManager.GetString("billContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcam.
        /// </summary>
        public static string camera {
            get {
                return ResourceManager.GetString("camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string changePwd {
            get {
                return ResourceManager.GetString("changePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại không chính xác.
        /// </summary>
        public static string correntPwdFail {
            get {
                return ResourceManager.GetString("correntPwdFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lần sử dụng.
        /// </summary>
        public static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        public static string createFAQ {
            get {
                return ResourceManager.GetString("createFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo người dùng thất bại.
        /// </summary>
        public static string createUserFail {
            get {
                return ResourceManager.GetString("createUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại không đúng.
        /// </summary>
        public static string currentPwdFalse {
            get {
                return ResourceManager.GetString("currentPwdFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc.
        /// </summary>
        public static string dateEnd {
            get {
                return ResourceManager.GetString("dateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hoàn thành.
        /// </summary>
        public static string dateFinish {
            get {
                return ResourceManager.GetString("dateFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày dự kiến.
        /// </summary>
        public static string dateManage {
            get {
                return ResourceManager.GetString("dateManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày báo cáo.
        /// </summary>
        public static string dateStaff {
            get {
                return ResourceManager.GetString("dateStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu.
        /// </summary>
        public static string dateStart {
            get {
                return ResourceManager.GetString("dateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hoàn thành.
        /// </summary>
        public static string dateTech {
            get {
                return ResourceManager.GetString("dateTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn chót.
        /// </summary>
        public static string deadline {
            get {
                return ResourceManager.GetString("deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu hạn chót.
        /// </summary>
        public static string deadlineRequire {
            get {
                return ResourceManager.GetString("deadlineRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn xóa câu hỏi - mã:.
        /// </summary>
        public static string deleteFAQ {
            get {
                return ResourceManager.GetString("deleteFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá người dùng.
        /// </summary>
        public static string deleteUser {
            get {
                return ResourceManager.GetString("deleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string describe {
            get {
                return ResourceManager.GetString("describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả của Quản lý.
        /// </summary>
        public static string describeTech {
            get {
                return ResourceManager.GetString("describeTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết đề nghị.
        /// </summary>
        public static string detailSug {
            get {
                return ResourceManager.GetString("detailSug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết công việc.
        /// </summary>
        public static string detailTask {
            get {
                return ResourceManager.GetString("detailTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết sự cố.
        /// </summary>
        public static string detailTrouble {
            get {
                return ResourceManager.GetString("detailTrouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thiết bị.
        /// </summary>
        public static string deviceCategory {
            get {
                return ResourceManager.GetString("deviceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thiết bị.
        /// </summary>
        public static string deviceName {
            get {
                return ResourceManager.GetString("deviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật người dùng thất bại.
        /// </summary>
        public static string editUserFail {
            get {
                return ResourceManager.GetString("editUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi !!! Vui lòng thử lại sau.
        /// </summary>
        public static string errorTryAgain {
            get {
                return ResourceManager.GetString("errorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thất bại.
        /// </summary>
        public static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi thường gặp.
        /// </summary>
        public static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức sửa.
        /// </summary>
        public static string fixMethod {
            get {
                return ResourceManager.GetString("fixMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng.
        /// </summary>
        public static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách sự cố.
        /// </summary>
        public static string headerTrouble {
            get {
                return ResourceManager.GetString("headerTrouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hoá đơn.
        /// </summary>
        public static string id_Bill {
            get {
                return ResourceManager.GetString("id_Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thiết bị.
        /// </summary>
        public static string id_device {
            get {
                return ResourceManager.GetString("id_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã người nhập báo cáo.
        /// </summary>
        public static string id_fill {
            get {
                return ResourceManager.GetString("id_fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã quản lý.
        /// </summary>
        public static string id_manage {
            get {
                return ResourceManager.GetString("id_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã người gặp sự cố.
        /// </summary>
        public static string id_report {
            get {
                return ResourceManager.GetString("id_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sự cố.
        /// </summary>
        public static string id_trouble {
            get {
                return ResourceManager.GetString("id_trouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã người dùng.
        /// </summary>
        public static string id_user {
            get {
                return ResourceManager.GetString("id_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Người Thêm FAQ.
        /// </summary>
        public static string idAddFAQ {
            get {
                return ResourceManager.GetString("idAddFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã câu hỏi.
        /// </summary>
        public static string idFAQ {
            get {
                return ResourceManager.GetString("idFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kỹ thuật viên.
        /// </summary>
        public static string idTech {
            get {
                return ResourceManager.GetString("idTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string insert {
            get {
                return ResourceManager.GetString("insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thất bại.
        /// </summary>
        public static string insertFail {
            get {
                return ResourceManager.GetString("insertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm câu hỏi.
        /// </summary>
        public static string insertFAQ {
            get {
                return ResourceManager.GetString("insertFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công.
        /// </summary>
        public static string insertSuccess {
            get {
                return ResourceManager.GetString("insertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hợp lệ.
        /// </summary>
        public static string invalid {
            get {
                return ResourceManager.GetString("invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn phím.
        /// </summary>
        public static string keyboard {
            get {
                return ResourceManager.GetString("keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vi.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức độ nghiêm trọng.
        /// </summary>
        public static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ít nghiêm trọng.
        /// </summary>
        public static string levelLess {
            get {
                return ResourceManager.GetString("levelLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xác định.
        /// </summary>
        public static string levelNo {
            get {
                return ResourceManager.GetString("levelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghiêm trọng.
        /// </summary>
        public static string levelSerious {
            get {
                return ResourceManager.GetString("levelSerious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rất Nghiêm trọng.
        /// </summary>
        public static string levelVery {
            get {
                return ResourceManager.GetString("levelVery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thiết bị.
        /// </summary>
        public static string manageDevice {
            get {
                return ResourceManager.GetString("manageDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý.
        /// </summary>
        public static string manager {
            get {
                return ResourceManager.GetString("manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý sự cố.
        /// </summary>
        public static string manageTrouble {
            get {
                return ResourceManager.GetString("manageTrouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý người dùng.
        /// </summary>
        public static string manageUser {
            get {
                return ResourceManager.GetString("manageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuột.
        /// </summary>
        public static string mouse {
            get {
                return ResourceManager.GetString("mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sự cố của tôi.
        /// </summary>
        public static string myTrouble {
            get {
                return ResourceManager.GetString("myTrouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người nhập báo cáo.
        /// </summary>
        public static string nameFill {
            get {
                return ResourceManager.GetString("nameFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên quản lý.
        /// </summary>
        public static string nameManage {
            get {
                return ResourceManager.GetString("nameManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người gặp sự cố.
        /// </summary>
        public static string nameReport {
            get {
                return ResourceManager.GetString("nameReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân Viên.
        /// </summary>
        public static string nameStaff {
            get {
                return ResourceManager.GetString("nameStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người đề nghị.
        /// </summary>
        public static string nameSug {
            get {
                return ResourceManager.GetString("nameSug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kỹ thuật viên.
        /// </summary>
        public static string nameTech {
            get {
                return ResourceManager.GetString("nameTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string newpwd {
            get {
                return ResourceManager.GetString("newpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo mới.
        /// </summary>
        public static string newReport {
            get {
                return ResourceManager.GetString("newReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thiết bị.
        /// </summary>
        public static string noDevice {
            get {
                return ResourceManager.GetString("noDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không ai.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có Task.
        /// </summary>
        public static string noTask {
            get {
                return ResourceManager.GetString("noTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        public static string oldpwd {
            get {
                return ResourceManager.GetString("oldpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công cộng.
        /// </summary>
        public static string pb {
            get {
                return ResourceManager.GetString("pb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy in.
        /// </summary>
        public static string printer {
            get {
                return ResourceManager.GetString("printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý.
        /// </summary>
        public static string process {
            get {
                return ResourceManager.GetString("process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riêng tư.
        /// </summary>
        public static string pv {
            get {
                return ResourceManager.GetString("pv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string pwd {
            get {
                return ResourceManager.GetString("pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối.
        /// </summary>
        public static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn xóa tham chiếu này.
        /// </summary>
        public static string removeRef {
            get {
                return ResourceManager.GetString("removeRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string removeSuccess {
            get {
                return ResourceManager.GetString("removeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        public static string renewpwd {
            get {
                return ResourceManager.GetString("renewpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay phần cứng.
        /// </summary>
        public static string replaceHardware {
            get {
                return ResourceManager.GetString("replaceHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề xuất.
        /// </summary>
        public static string request {
            get {
                return ResourceManager.GetString("request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt buộc.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải quyết lỗi.
        /// </summary>
        public static string resolveTrouble {
            get {
                return ResourceManager.GetString("resolveTrouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thay đổi.
        /// </summary>
        public static string saveChange {
            get {
                return ResourceManager.GetString("saveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màn hình.
        /// </summary>
        public static string screen {
            get {
                return ResourceManager.GetString("screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm ....
        /// </summary>
        public static string seemore {
            get {
                return ResourceManager.GetString("seemore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hình ảnh.
        /// </summary>
        public static string selectImage {
            get {
                return ResourceManager.GetString("selectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi trả.
        /// </summary>
        public static string sendBack {
            get {
                return ResourceManager.GetString("sendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân chia sự cố.
        /// </summary>
        public static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        public static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string statusFinish {
            get {
                return ResourceManager.GetString("statusFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hoàn thành.
        /// </summary>
        public static string statusManagerFinish {
            get {
                return ResourceManager.GetString("statusManagerFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        public static string statusManagerProcess {
            get {
                return ResourceManager.GetString("statusManagerProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã phân công.
        /// </summary>
        public static string statusManagerReceived {
            get {
                return ResourceManager.GetString("statusManagerReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo mới.
        /// </summary>
        public static string statusManagerSend {
            get {
                return ResourceManager.GetString("statusManagerSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        public static string statusProcess {
            get {
                return ResourceManager.GetString("statusProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nhận.
        /// </summary>
        public static string statusRecevied {
            get {
                return ResourceManager.GetString("statusRecevied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi.
        /// </summary>
        public static string statusSend {
            get {
                return ResourceManager.GetString("statusSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi lại.
        /// </summary>
        public static string statusSendBack {
            get {
                return ResourceManager.GetString("statusSendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang sử lí sự cố.
        /// </summary>
        public static string statusTroubleshooting {
            get {
                return ResourceManager.GetString("statusTroubleshooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đi.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề nghị câu hỏi.
        /// </summary>
        public static string suggestionFAQ {
            get {
                return ResourceManager.GetString("suggestionFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công việc.
        /// </summary>
        public static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả công việc.
        /// </summary>
        public static string taskDes {
            get {
                return ResourceManager.GetString("taskDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả của KTV.
        /// </summary>
        public static string techDes {
            get {
                return ResourceManager.GetString("techDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỹ thuật viên.
        /// </summary>
        public static string technician {
            get {
                return ResourceManager.GetString("technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian hoàn thành (Ngày).
        /// </summary>
        public static string timeFinish {
            get {
                return ResourceManager.GetString("timeFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo lỗi.
        /// </summary>
        public static string trouble {
            get {
                return ResourceManager.GetString("trouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ Quản lý.
        /// </summary>
        public static string troubleManagerPage {
            get {
                return ResourceManager.GetString("troubleManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham chiếu sự cố.
        /// </summary>
        public static string troubleRef {
            get {
                return ResourceManager.GetString("troubleRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường hợp tương tự.
        /// </summary>
        public static string troubleReference {
            get {
                return ResourceManager.GetString("troubleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khắc phục sự cố.
        /// </summary>
        public static string troubleShooting {
            get {
                return ResourceManager.GetString("troubleShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ Kỹ thuật viên.
        /// </summary>
        public static string troubleTechPage {
            get {
                return ResourceManager.GetString("troubleTechPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại.
        /// </summary>
        public static string updateFail {
            get {
                return ResourceManager.GetString("updateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string updateSuccess {
            get {
                return ResourceManager.GetString("updateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người dùng.
        /// </summary>
        public static string userInfo {
            get {
                return ResourceManager.GetString("userInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý người dùng.
        /// </summary>
        public static string userManager {
            get {
                return ResourceManager.GetString("userManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi không được trống.
        /// </summary>
        public static string validationSuggestFAQ {
            get {
                return ResourceManager.GetString("validationSuggestFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu trả lời không được trống.
        /// </summary>
        public static string validationSuggestFAQAns {
            get {
                return ResourceManager.GetString("validationSuggestFAQAns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
    }
}
